name: Release extension ZIP

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r tickrtools.zip . \
            --exclude "*.git*" \
            --exclude ".github/*" \
            --exclude "*.md" \
            --exclude "*.pem"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: tickrtools.zip
          make_latest: true
